// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1782406811);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.jxl", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1782406808);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 172);
user_pref("browser.newtabpage.activity-stream.impressionId", "{23ce011d-6264-4a8b-8aa5-0dbafcd2b1aa}");
user_pref("browser.newtabpage.activity-stream.newtabWallpapers.user.enabled.migrated", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1782406810);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1782406812574");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1782428412574");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20260618123659");
user_pref("browser.startup.homepage_override.mstone", "152.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1782406810);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"],\"zen-sidebar-top-buttons\":[\"zen-toggle-compact-mode\"],\"zen-sidebar-foot-buttons\":[\"downloads-button\",\"zen-workspaces-button\",\"zen-create-new-button\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"zen-sidebar-foot-buttons\",\"PersonalToolbar\"],\"currentVersion\":24,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 7);
user_pref("captchadetection.lastSubmission", 1782406);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "95ed6f2d-3528-4d83-a6ab-78f819f2d4b3");
user_pref("datareporting.dau.cachedUsageProfileID", "645a5430-1c0a-4fb4-9c9b-286bb05744bb");
user_pref("distribution.iniFile.exists.appversion", "1.21.3b");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "ff382279db2f43098703051b7e5dc0d2");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.lastAppBuildId", "20260618123659");
user_pref("extensions.lastAppVersion", "1.21.3b");
user_pref("extensions.lastPlatformVersion", "152.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"579c8b8c-56e1-4b7b-b421-6b968fa7361f\",\"formautofill@mozilla.org\":\"ca1d907f-f22d-43c6-95d9-0fd26d3cc845\",\"ipp-activator@mozilla.com\":\"b1fc77d4-1873-482c-a5af-9c3cdfe48ca7\",\"pictureinpicture@mozilla.org\":\"e481b076-39c9-4e23-8565-3dd1ba55d9bc\",\"addons-search-detection@mozilla.com\":\"a655d1ce-67b9-4e49-8a8c-2b9e23d37d74\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"26712a9a-da1a-4575-9455-6b75bf3ca7ab\",\"default-theme@mozilla.org\":\"23f8f587-4cc7-4344-84a2-751a1b337ac7\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.firstUpdateComplete", true);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 3);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "e32aed95-b1eb-4a9b-9bbc-19bc64e18e1a");
user_pref("nimbus.rollouts.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.globalprivacycontrol.was_ever_enabled", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("privacy.trackingprotection.allow_list.hasUserInteractedWithETPSettings", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"bookmarksExpandedFolders\":[],\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.profiles.storeID", "df3036cc");
user_pref("toolkit.startup.last_success", 1782406807);
user_pref("toolkit.telemetry.cachedClientID", "10396e8a-55b3-4571-8326-4081154dc8b1");
user_pref("toolkit.telemetry.cachedProfileGroupID", "8ca85332-6b5a-45c4-aed8-7783e59c391b");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("zen.keyboard.shortcuts.version", 19);
user_pref("zen.mods.last-update", 1782406810);
user_pref("zen.mods.milestone", "1.21.3b");
user_pref("zen.mods.updated-value-observer", true);
user_pref("zen.session-store.last-build-id", "20260618123659");
user_pref("zen.ui.migration.compact-mode-button-added", true);
user_pref("zen.ui.migration.version", 6);
user_pref("zen.updates.last-build-id", "20260618123659");
user_pref("zen.updates.last-version", "1.21.3b");
user_pref("zen.welcome-screen.seen", true);
user_pref("zen.workspaces.active", "{5c57eec6-9420-49b0-b334-4e38d411e639}");
