plasmarc|Theme|name=RGFya2x5
kdeglobals|KDE|widgetStyle=ZGFya2x5
kdeglobals|General|ColorScheme=TWF0ZXJpYWxZb3VEYXJr
kwinrc|org.kde.kdecoration2|library=b3JnLmtkZS5kYXJrbHk=
kwinrc|org.kde.kdecoration2|theme=QGRhcmtseQ==
kcminputrc|Mouse|cursorTheme=QmliYXRhLU1vZGVybi1JY2U=
